### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by pschlitzer** [djinteractive/Lightbox-for-Bootstrap#1]
Awesome looking plugin! I haven't had time to look through the files or downloaded it yet but will probably will test drive it after work. I was just curious if changing any of the css attributes to percentages so that it's responsive would prevent it from working properly??

-Pat

**Comment by pschlitzer** [comment]
Or what would the best way to make it responsive be? The example did not respond when I changed the window size.
Thanks!

**Comment by djinteractive** [comment]
I've just pushed through some code that should resolve this issue.
