### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by thannes30** [djinteractive/Lightbox-for-Bootstrap#3]
Hey man, I love your idea, and great job creating this lighbox as the other ones I've found really suck. Only thing I wish you'd do differently is change the way you explain it. Your readme tutorial is not very clear at all. It took me around 30 minutes to figure out what you were saying in the 5 steps and get them working... I had to visit your site many times and view source, and inspect element. I wish you would have included the full snippet of code in the readme. Other than that, great job!

**Comment by djinteractive** [comment]
Thanks, I'm glad you found it useful. I should note that the readme file was never intended to be a tutorial, it is nothing more than a summary of what the app does and assumes you know the bootstrap markup. I use a very early version of the plugin on my own site so it really wasn't the place to figure out how this works, this project is actually based on what I did to get it functioning and has a number of improvements over it. You can find the actual tutorial/examples are in the included index.html page, complete with all the code to get it working very quickly.
